version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/demo_db
    volumes:
      - ./app:/usr/src/app  # Mount the app directory for hot reloading

  ui:
    build:
      context: ./ui
    ports:
      - "4200:4200"
    depends_on:
      - app
    volumes:
      - ./ui:/usr/src/app # Mount the app directory for hot reloading

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Mount a volume for MongoDB data persistence

volumes:
  mongo-data:  # Define the named volume for MongoDB data
